; this is a lisp file
; (defmacro setTo10(num)
; (set num 10)(print num))
(defvar x 25)
(write x)
(write-line "")
; (setTo10 x)
; moving on...
; int x = 7*(2+5)
(write-line "Starting defvar")
(defvar y (* (+ 2 5) 7))
(write y)
(write-line "")
(write-line "This is a lisp program")
(write-line "Defining Macro")
(defmacro tester (num)
(set num 10)(print num))
(defvar z 25)
(tester z)
(write-line "Using eq")
(write (eq x z))